class libmono {
  package{'libmono-2.0-1': }
  package{'libmono-2.0-dev': }
  package{'libmono-accessibility4.0-cil': }
  package{'libmono-c5-1.1-cil': }
  package{'libmono-cairo4.0-cil': }
  package{'libmono-cecil-private-cil': }
  package{'libmono-cil-dev': }
  package{'libmono-codecontracts4.0-cil': }
  package{'libmono-compilerservices-symbolwriter4.0-cil': }
  package{'libmono-corlib4.5-cil': }
  package{'libmono-csharp4.0c-cil': }
  package{'libmono-custommarshalers4.0-cil': }
  package{'libmono-data-tds4.0-cil': }
  package{'libmono-db2-1.0-cil': }
  package{'libmono-debugger-soft4.0a-cil': }
  package{'libmono-http4.0-cil': }
  package{'libmono-i18n-cjk4.0-cil': }
  package{'libmono-i18n-mideast4.0-cil': }
  package{'libmono-i18n-other4.0-cil': }
  package{'libmono-i18n-rare4.0-cil': }
  package{'libmono-i18n-west4.0-cil': }
  package{'libmono-i18n4.0-all': }
  package{'libmono-i18n4.0-cil': }
  package{'libmono-ldap4.0-cil': }
  package{'libmono-management4.0-cil': }
  package{'libmono-messaging-rabbitmq4.0-cil': }
  package{'libmono-messaging4.0-cil': }
  package{'libmono-microsoft-build-engine4.0-cil': }
  package{'libmono-microsoft-build-framework4.0-cil': }
  package{'libmono-microsoft-build-tasks-v4.0-4.0-cil': }
  package{'libmono-microsoft-build-utilities-v4.0-4.0-cil': }
  package{'libmono-microsoft-build4.0-cil': }
  package{'libmono-microsoft-csharp4.0-cil': }
  package{'libmono-microsoft-visualc10.0-cil': }
  package{'libmono-microsoft-web-infrastructure1.0-cil': }
  package{'libmono-oracle4.0-cil': }
  package{'libmono-parallel4.0-cil': }
  package{'libmono-peapi4.0a-cil': }
  package{'libmono-posix4.0-cil': }
  package{'libmono-profiler': }
  package{'libmono-rabbitmq4.0-cil': }
  package{'libmono-relaxng4.0-cil': }
  package{'libmono-security4.0-cil': }
  package{'libmono-sharpzip4.84-cil': }
  package{'libmono-simd4.0-cil': }
  package{'libmono-sqlite4.0-cil': }
  package{'libmono-system-componentmodel-composition4.0-cil': }
  package{'libmono-system-componentmodel-dataannotations4.0-cil': }
  package{'libmono-system-configuration-install4.0-cil': }
  package{'libmono-system-configuration4.0-cil': }
  package{'libmono-system-core4.0-cil': }
  package{'libmono-system-data-datasetextensions4.0-cil': }
  package{'libmono-system-data-linq4.0-cil': }
  package{'libmono-system-data-services-client4.0-cil': }
  package{'libmono-system-data-services4.0-cil': }
  package{'libmono-system-data4.0-cil': }
  package{'libmono-system-design4.0-cil': }
  package{'libmono-system-drawing-design4.0-cil': }
  package{'libmono-system-drawing4.0-cil': }
  package{'libmono-system-dynamic4.0-cil': }
  package{'libmono-system-enterpriseservices4.0-cil': }
  package{'libmono-system-identitymodel-selectors4.0-cil': }
  package{'libmono-system-identitymodel4.0-cil': }
  package{'libmono-system-io-compression-filesystem4.0-cil': }
  package{'libmono-system-io-compression4.0-cil': }
  package{'libmono-system-json-microsoft4.0-cil': }
  package{'libmono-system-json4.0-cil': }
  package{'libmono-system-ldap-protocols4.0-cil': }
  package{'libmono-system-ldap4.0-cil': }
  package{'libmono-system-management4.0-cil': }
  package{'libmono-system-messaging4.0-cil': }
  package{'libmono-system-net-http-formatting4.0-cil': }
  package{'libmono-system-net-http-webrequest4.0-cil': }
  package{'libmono-system-net-http4.0-cil': }
  package{'libmono-system-net4.0-cil': }
  package{'libmono-system-numerics4.0-cil': }
  package{'libmono-system-reactive-core2.2-cil': }
  package{'libmono-system-reactive-debugger2.2-cil': }
  package{'libmono-system-reactive-experimental2.2-cil': }
  package{'libmono-system-reactive-interfaces2.2-cil': }
  package{'libmono-system-reactive-linq2.2-cil': }
  package{'libmono-system-reactive-observable-aliases0.0-cil': }
  package{'libmono-system-reactive-platformservices2.2-cil': }
  package{'libmono-system-reactive-providers2.2-cil': }
  package{'libmono-system-reactive-runtime-remoting2.2-cil': }
  package{'libmono-system-reactive-windows-forms2.2-cil': }
  package{'libmono-system-reactive-windows-threading2.2-cil': }
  package{'libmono-system-runtime-caching4.0-cil': }
  package{'libmono-system-runtime-durableinstancing4.0-cil': }
  package{'libmono-system-runtime-serialization-formatters-soap4.0-cil': }
  package{'libmono-system-runtime-serialization4.0-cil': }
  package{'libmono-system-runtime4.0-cil': }
  package{'libmono-system-security4.0-cil': }
  package{'libmono-system-servicemodel-activation4.0-cil': }
  package{'libmono-system-servicemodel-discovery4.0-cil': }
  package{'libmono-system-servicemodel-routing4.0-cil': }
  package{'libmono-system-servicemodel-web4.0-cil': }
  package{'libmono-system-servicemodel4.0a-cil': }
  package{'libmono-system-serviceprocess4.0-cil': }
  package{'libmono-system-threading-tasks-dataflow4.0-cil': }
  package{'libmono-system-transactions4.0-cil': }
  package{'libmono-system-web-abstractions4.0-cil': }
  package{'libmono-system-web-applicationservices4.0-cil': }
  package{'libmono-system-web-dynamicdata4.0-cil': }
  package{'libmono-system-web-extensions-design4.0-cil': }
  package{'libmono-system-web-extensions4.0-cil': }
  package{'libmono-system-web-http-selfhost4.0-cil': }
  package{'libmono-system-web-http-webhost4.0-cil': }
  package{'libmono-system-web-http4.0-cil': }
  package{'libmono-system-web-mvc3.0-cil': }
  package{'libmono-system-web-razor2.0-cil': }
  package{'libmono-system-web-routing4.0-cil': }
  package{'libmono-system-web-services4.0-cil': }
  package{'libmono-system-web-webpages-deployment2.0-cil': }
  package{'libmono-system-web-webpages-razor2.0-cil': }
  package{'libmono-system-web-webpages2.0-cil': }
  package{'libmono-system-web4.0-cil': }
  package{'libmono-system-windows-forms-datavisualization4.0a-cil': }
  package{'libmono-system-windows-forms4.0-cil': }
  package{'libmono-system-windows4.0-cil': }
  package{'libmono-system-xaml4.0-cil': }
  package{'libmono-system-xml-linq4.0-cil': }
  package{'libmono-system-xml-serialization4.0-cil': }
  package{'libmono-system-xml4.0-cil': }
  package{'libmono-system4.0-cil': }
  package{'libmono-tasklets4.0-cil': }
  package{'libmono-webbrowser4.0-cil': }
  package{'libmono-webmatrix-data4.0-cil': }
  package{'libmono-windowsbase4.0-cil': }
  package{'libmono-xbuild-tasks4.0-cil': }
  package{'libmonoboehm-2.0-1': }
  package{'libmonoboehm-2.0-dev': }
  package{'libmonosgen-2.0-1': }
}
