node default {
  include ::libakonadi
  include ::lib32
  include ::krb5
  include ::kde
  include ::isc-dhcp
  include ::iproute
  include ::init
  include ::icedtea
  include ::imagemagick
  include ::gvfs
  include ::gstreamer
  include ::groff
  include ::users
  include ::homedir
  include ::acl  
  include ::acpi
  include ::adduser
  include ::adwaita-icon-theme
  include ::akonadi-backend-mysql  
  include ::analog
  include ::ant
  include ::apache
  include ::apt-pkg
  include ::aspell
  include ::at
  include ::attr
  include ::autoconf
  include ::automake
  include ::autopoint
  include ::autotools-dev
  include ::avahi-daemon
  include ::base
  include ::bash
  include ::bin
  include ::bsd
  include ::bzip2
  include ::ca-certificates
  include ::colord
  include ::console
  include ::cpp
  include ::cups
  include ::dbus
  include ::dconf
  include ::debconf
  include ::debian
  include ::discover
  include ::dm
  include ::doc
  include ::dovecot
  include ::dpkg
  include ::e2fs
  include ::erlang
  include ::exim4
  include ::font
  include ::foomatic
  include ::gpp
  include ::gcc
  include ::gconf
  include ::gdb
  include ::gettext
  include ::gfortran
  include ::gir
  include ::git
  include ::glib
  include ::gnupg
  include ::perfmon
  include ::services
  include ::grub
  include ::mysql

  include ::all-other-pkgs
}
