class xserver {
  package{'xserver-common': }
  package{'xserver-xorg': }
  package{'xserver-xorg-core': }
  package{'xserver-xorg-input-all': }
  package{'xserver-xorg-input-evdev': }
  package{'xserver-xorg-input-mouse': }
  package{'xserver-xorg-input-synaptics': }
  package{'xserver-xorg-input-wacom': }
  package{'xserver-xorg-video-all': }
  package{'xserver-xorg-video-ati': }
  package{'xserver-xorg-video-cirrus': }
  package{'xserver-xorg-video-fbdev': }
  package{'xserver-xorg-video-intel': }
  package{'xserver-xorg-video-mach64': }
  package{'xserver-xorg-video-mga': }
  package{'xserver-xorg-video-modesetting': }
  package{'xserver-xorg-video-neomagic': }
  package{'xserver-xorg-video-nouveau': }
  package{'xserver-xorg-video-openchrome': }
  package{'xserver-xorg-video-qxl': }
  package{'xserver-xorg-video-r128': }
  package{'xserver-xorg-video-radeon': }
  package{'xserver-xorg-video-savage': }
  package{'xserver-xorg-video-siliconmotion': }
  package{'xserver-xorg-video-sisusb': }
  package{'xserver-xorg-video-tdfx': }
  package{'xserver-xorg-video-trident': }
  package{'xserver-xorg-video-vesa': }
  package{'xserver-xorg-video-vmware': }
}
