class python {
  package{'libpython-dev': }
  package{'libpython-stdlib': }
  package{'libpython2.7': }
  package{'libpython2.7-dev': }
  package{'libpython2.7-minimal': }
  package{'libpython2.7-stdlib': }
  package{'libpython3-dev': }
  package{'libpython3-stdlib': }
  
  package{'python': }
  package{'python-amqp': }
  package{'python-amqplib': }
  package{'python-antlr': }
  package{'python-anyjson': }
  package{'python-apt': }
  package{'python-apt-common': }
  package{'python-billiard': }
  package{'python-bs4': }
  package{'python-cairo': }
  package{'python-celery': }
  package{'python-chardet': }
  package{'python-crypto': }
  package{'python-dateutil': }
  package{'python-decorator': }
  package{'python-dev': }
  package{'python-django': }
  package{'python-django-celery': }
  package{'python-django-common': }
  package{'python-django-pagination': }
  package{'python-django-picklefield': }
  package{'python-django-south': }
  package{'python-dnspython': }
  package{'python-egenix-mxdatetime': }
  package{'python-egenix-mxtools': }
  package{'python-glade2': }
  package{'python-gmpy': }
  package{'python-gobject-2': }
  package{'python-gtk2': }
  package{'python-html5lib': }
  package{'python-imaging': }
  package{'python-joblib': }
  package{'python-kombu': }
  package{'python-ldb': }
  package{'python-lxml': }
  package{'python-mailer': }
  package{'python-markdown': }
  package{'python-matplotlib-data': }
  package{'python-memcache': }
  package{'python-minimal': }
  package{'python-nose': }
  package{'python-ntdb': }
  package{'python-numexpr': }
  package{'python-numpy': }
  package{'python-openid': }
  package{'python-openpyxl': }
  package{'python-pandas': }
  package{'python-pandas-lib': }
  package{'python-pexpect': }
  package{'python-pil': }
  package{'python-pkg-resources': }
  package{'python-psycopg2': }
  package{'python-pygments': }
  package{'python-pyicu': }
  package{'python-pyparsing': }
  package{'python-renderpm': }
  package{'python-reportlab': }
  package{'python-reportlab-accel': }
  package{'python-samba': }
  package{'python-scipy': }
  package{'python-setuptools': }
  package{'python-simplegeneric': }
  package{'python-simplejson': }
  package{'python-six': }
  package{'python-sklearn': }
  package{'python-sklearn-lib': }
  package{'python-software-properties': }
  package{'python-sqlparse': }
  package{'python-statsmodels': }
  package{'python-statsmodels-lib': }
  package{'python-support': }
  package{'python-talloc': }
  package{'python-tdb': }
  package{'python-tz': }
  package{'python-xlrd': }
  package{'python-xlwt': }
  package{'python-yaml': }
  package{'python2.7': }
  package{'python2.7-dev': }
  package{'python2.7-minimal': }
  package{'python3': }
  package{'python3-apt': }
  package{'python3-aptdaemon': }
  package{'python3-aptdaemon.gtk3widgets': }
  package{'python3-chardet': }
  package{'python3-colorama': }
  package{'python3-dbus': }
  package{'python3-defer': }
  package{'python3-dev': }
  package{'python3-distlib': }
  package{'python3-gi': }
  package{'python3-html5lib': }
  package{'python3-minimal': }
  package{'python3-pip': }
  package{'python3-pkg-resources': }
  package{'python3-requests': }
  package{'python3-setuptools': }
  package{'python3-six': }
  package{'python3-software-properties': }
  package{'python3-urllib3': }
  package{'python3-wheel': }
  package{'python3.4': }
}
