class allotherpkgs {
  package{'bc': }
  package{'bison': }
  package{'bridge-utils': }
  package{'btyacc': }
  package{'build-essential': }
  package{'busybox': }
  package{'ccache': }
  package{'cdbs': }
  package{'cifs-utils': }
  package{'cli-common': }
  package{'comerr-dev': }
  package{'coreutils': }
  package{'cpio': }
  package{'cron': }
  package{'cryptsetup-bin': }
  package{'curl': }
  package{'dash': }
  package{'db5.1-util': }
  package{'dc': }
  package{'debhelper': }
  package{'debootstrap': }
  package{'debugedit': }
  package{'desktop-file-utils': }
  package{'dh-python': }
  package{'dictionaries-common': }
  package{'diffutils': }
  package{'dnsutils': }
  package{'dosfstools': }
  package{'eject': }
  package{'emacsen-common': }
  package{'enchant': }
  package{'ethtool': }
  package{'exuberant-ctags': }
  package{'fakeroot': }
  package{'file': }
  package{'findutils': }
  package{'firmware-linux-free': }
  package{'flex': }
  package{'ftp': }
  package{'fuse': }
  package{'gamin': }
  package{'gawk': }
  package{'gdisk': }
  package{'geoclue-2.0': }
  package{'geoip-database': }
  package{'ghostscript': }
  package{'gnome-mime-data': }
  package{'gperf': }
  package{'gpgv': }
  package{'graphviz': }
  package{'grep': }
  package{'gsettings-desktop-schemas': }
  package{'gsfonts': }
  package{'gunicorn': }
  package{'gzip': }
  package{'hdparm': }
  package{'hicolor-icon-theme': }
  package{'host': }
  package{'hostname': }
  package{'hp-ppd': }
  package{'hplip': }
  package{'hunspell-en-us': }
  package{'iamerican': }
  package{'ibritish': }
  package{'ienglish-common': }
  package{'ifupdown': }
  package{'info': }
  package{'insserv': }
  package{'install-info': }
  package{'installation-report': }
  package{'intltool-debian': }
  package{'iptables': }
  package{'iputils-ping': }
  package{'ipxe-qemu': }
  package{'ipython': }
  package{'irqbalance': }
  package{'iso-codes': }
  package{'ispell': }
  package{'java-common': }
  package{'javascript-common': }
  package{'junit': }
  package{'kate-data': }
  package{'kbd': }
  package{'keyboard-configuration': }
  package{'keyutils': }
  package{'klibc-utils': }
  package{'kmod': }
  package{'ksysguard': }
  package{'ksysguardd': }
  package{'laptop-detect': }
  package{'less': }
  package{'liba52-0.7.4': }
  package{'libaa1': }
  package{'libaacs0': }
  package{'libacl1': }
  package{'libaio1': }
  package{'libalgorithm-diff-perl': }
  package{'libalgorithm-diff-xs-perl': }
  package{'libalgorithm-merge-perl': }
  package{'libamd2.3.1': }
  package{'libapache2-mod-xsendfile': }
  package{'libapr1': }
  package{'libaprutil1': }
  package{'libaprutil1-dbd-sqlite3': }
  package{'libaprutil1-ldap': }
  package{'libapt-inst1.5': }
  package{'libapt-pkg4.12': }
  package{'libarchive-extract-perl': }
  package{'libart-2.0-2': }
  package{'libasan1': }
  package{'libasn1-8-heimdal': }
  package{'libasound2': }
  package{'libasound2-data': }
  package{'libasound2-dev': }
  package{'libaspell15': }
  package{'libasprintf-dev': }
  package{'libass5': }
  package{'libassuan0': }
  package{'libasyncns0': }
  package{'libatasmart4': }
  package{'libatk-bridge2.0-0': }
  package{'libatk-wrapper-java': }
  package{'libatk-wrapper-java-jni': }
  package{'libatk1.0-0': }
  package{'libatk1.0-data': }
  package{'libatm1': }
  package{'libatomic1': }
  package{'libatspi2.0-0': }
  package{'libattica0.4': }
  package{'libattr1': }
  package{'libaudit-common': }
  package{'libaudit1': }
  package{'libauthen-sasl-perl': }
  package{'libavahi-client3': }
  package{'libavahi-common-data': }
  package{'libavahi-common3': }
  package{'libavahi-core7': }
  package{'libavahi-glib1': }
  package{'libavc1394-0': }
  package{'libavcodec56': }
  package{'libavformat56': }
  package{'libavresample2': }
  package{'libavutil54': }
  package{'libbasicusageenvironment0': }
  package{'libblas-common': }
  package{'libblas-dev': }
  package{'libblas3': }
  package{'libblkid1': }
  package{'libbluetooth3': }
  package{'libbluray1': }
  package{'libbonobo2-0': }
  package{'libbonobo2-common': }
  package{'libbonoboui2-0': }
  package{'libbonoboui2-common': }
  package{'libbrlapi0.6': }
  package{'libbsd0': }
  package{'libbz2-1.0': }
  package{'libbz2-dev': }
  package{'libc-bin': }
  package{'libc-dev-bin': }
  package{'libc6': }
  package{'libc6-dbg': }
  package{'libc6-dev': }
  package{'libc6-dev-i386': }
  package{'libc6-dev-x32': }
  package{'libc6-i386': }
  package{'libc6-x32': }
  package{'libcaca0': }
  package{'libcairo-gobject2': }
  package{'libcairo-perl': }
  package{'libcairo-script-interpreter2': }
  package{'libcairo2': }
  package{'libcanberra-gtk3-0': }
  package{'libcanberra0': }
  package{'libcap-ng0': }
  package{'libcap2': }
  package{'libcap2-bin': }
  package{'libcddb2': }
  package{'libcdio13': }
  package{'libcdparanoia0': }
  package{'libcdt5': }
  package{'libcgi-fast-perl': }
  package{'libcgi-pm-perl': }
  package{'libcgraph6': }
  package{'libchromaprint0': }
  package{'libcilkrts5': }
  package{'libck-connector0': }
  package{'libclass-isa-perl': }
  package{'libcln6': }
  package{'libcloog-isl4': }
  package{'libcolamd2.8.0': }
  package{'libcolord2': }
  package{'libcolorhug2': }
  package{'libcomerr2': }
  package{'libconfig-inifiles-perl': }
  package{'libcpan-meta-perl': }
  package{'libcppunit-dev': }
  package{'libcroco3': }
  package{'libcryptsetup4': }
  package{'libcrystalhd3': }
  package{'libcups2': }
  package{'libcupscgi1': }
  package{'libcupsfilters1': }
  package{'libcupsimage2': }
  package{'libcupsmime1': }
  package{'libcupsppdc1': }
  package{'libcurl3': }
  package{'libcurl3-gnutls': }
  package{'libcurl4-openssl-dev': }
  package{'libdaemon0': }
  package{'libdata-uuid-perl': }
  package{'libdata-validate-domain-perl': }
  package{'libdata-validate-ip-perl': }
  package{'libdata-validate-uri-perl': }
  package{'libdatrie1': }
  package{'libdb5.3': }
  package{'libdbd-mysql-perl': }
  package{'libdbi-perl': }
  package{'libdbus-1-3': }
  package{'libdbus-1-dev': }
  package{'libdbus-glib-1-2': }
  package{'libdbusmenu-qt2': }
  package{'libdc1394-22': }
  package{'libdca0': }
  package{'libdconf1': }
  package{'libdebconfclient0': }
  package{'libdevmapper-event1.02.1': }
  package{'libdevmapper1.02.1': }
  package{'libdigest-hmac-perl': }
  package{'libdirac-decoder0': }
  package{'libdirac-encoder0': }
  package{'libdirectfb-1.2-9': }
  package{'libdiscover2': }
  package{'libdjvulibre-text': }
  package{'libdjvulibre21': }
  package{'libdlrestrictions1': }
  package{'libdmtx0a': }
  package{'libdns-export100': }
  package{'libdns100': }
  package{'libdpkg-perl': }
  package{'libdrm-dev': }
  package{'libdrm-intel1': }
  package{'libdrm-nouveau2': }
  package{'libdrm-radeon1': }
  package{'libdrm2': }
  package{'libdsdp-5.8gf': }
  package{'libdv4': }
  package{'libdvbpsi9': }
  package{'libdvdnav4': }
  package{'libdvdread4': }
  package{'libdw1': }
  package{'libedit2': }
  package{'libegl1-mesa': }
  package{'libegl1-mesa-drivers': }
  package{'libelf1': }
  package{'libelfg0': }
  package{'libenca0': }
  package{'libenchant1c2a': }
  package{'libencode-locale-perl': }
  package{'libepoxy0': }
  package{'libept1.4.12': }
  package{'liberror-perl': }
  package{'libestr0': }
  package{'libevdev2': }
  package{'libevent-2.0-5': }
  package{'libexif12': }
  package{'libexiv2-13': }
  package{'libexpat1': }
  package{'libexpat1-dev': }
  package{'libexpect-perl': }
  package{'libfaad2': }
  package{'libfakeroot': }
  package{'libfam0': }
  package{'libfcgi-perl': }
  package{'libfdt1': }
  package{'libffi6': }
  package{'libfftw3-double3': }
  package{'libfile-basedir-perl': }
  package{'libfile-copy-recursive-perl': }
  package{'libfile-desktopentry-perl': }
  package{'libfile-fcntllock-perl': }
  package{'libfile-listing-perl': }
  package{'libfile-mimeinfo-perl': }
  package{'libfile-slurp-perl': }
  package{'libfile-which-perl': }
  package{'libfl-dev': }
  package{'libflac8': }
  package{'libfont-afm-perl': }
  package{'libfontconfig1': }
  package{'libfontembed1': }
  package{'libfontenc1': }
  package{'libfreetype6': }
  package{'libfreetype6-dev': }
  package{'libfribidi0': }
  package{'libfs6': }
  package{'libfuse2': }
  package{'libgail18': }
  package{'libgamin0': }
  package{'libgbm1': }
  package{'libgc1c2': }
  package{'libgcc-4.9-dev': }
  package{'libgcc1': }
  package{'libgconf-2-4': }
  package{'libgconf2-4': }
  package{'libgcrypt20': }
  package{'libgcrypt20-dev': }
  package{'libgd3': }
  package{'libgdbm3': }
  package{'libgdiplus': }
  package{'libgdk-pixbuf2.0-0': }
  package{'libgdk-pixbuf2.0-common': }
  package{'libgeoip1': }
  package{'libgettextpo-dev': }
  package{'libgettextpo0': }
  package{'libgfortran-4.9-dev': }
  package{'libgfortran3': }
  package{'libgif4': }
  package{'libgirepository-1.0-1': }
  package{'libgl1-mesa-dev': }
  package{'libgl1-mesa-dri': }
  package{'libgl1-mesa-glx': }
  package{'libglade2-0': }
  package{'libglade2.0-cil': }
  package{'libglapi-mesa': }
  package{'libgles1-mesa': }
  package{'libgles2-mesa': }
  package{'libglew1.10': }
  package{'libglib-perl': }
  package{'libglib2.0-0': }
  package{'libglib2.0-bin': }
  package{'libglib2.0-cil': }
  package{'libglib2.0-data': }
  package{'libglpk36': }
  package{'libglu1-mesa': }
  package{'libgmp-dev': }
  package{'libgmp10': }
  package{'libgmpxx4ldbl': }
  package{'libgnome-2-0': }
  package{'libgnome-keyring-common': }
  package{'libgnome-keyring0': }
  package{'libgnome2-0': }
  package{'libgnome2-bin': }
  package{'libgnome2-common': }
  package{'libgnomecanvas2-0': }
  package{'libgnomecanvas2-common': }
  package{'libgnomeui-0': }
  package{'libgnomeui-common': }
  package{'libgnomevfs2-0': }
  package{'libgnomevfs2-common': }
  package{'libgnomevfs2-extra': }
  package{'libgnutls-deb0-28': }
  package{'libgnutls-openssl27': }
  package{'libgnutls28-dev': }
  package{'libgnutlsxx28': }
  package{'libgomp1': }
  package{'libgpg-error-dev': }
  package{'libgpg-error0': }
  package{'libgpgme11': }
  package{'libgphoto2-6': }
  package{'libgphoto2-port10': }
  package{'libgpm2': }
  package{'libgps21': }
  package{'libgraph-perl': }
  package{'libgraphite2-3': }
  package{'libgroupsock1': }
  package{'libgs9': }
  package{'libgs9-common': }
  package{'libgsl0ldbl': }
  package{'libgsm1': }
  package{'libgssapi-krb5-2': }
  package{'libgssapi3-heimdal': }
  package{'libgssglue1': }
  package{'libgssrpc4': }
  package{'libgtk-3-0': }
  package{'libgtk-3-bin': }
  package{'libgtk-3-common': }
  package{'libgtk2-perl': }
  package{'libgtk2.0-0': }
  package{'libgtk2.0-bin': }
  package{'libgtk2.0-cil': }
  package{'libgtk2.0-common': }
  package{'libgudev-1.0-0': }
  package{'libgusb2': }
  package{'libgutenprint2': }
  package{'libgvc6': }
  package{'libgvpr2': }
  package{'libharfbuzz-gobject0': }
  package{'libharfbuzz-icu0': }
  package{'libharfbuzz0b': }
  package{'libhcrypto4-heimdal': }
  package{'libhdb9-heimdal': }
  package{'libhdf5-8': }
  package{'libheap-perl': }
  package{'libheimbase1-heimdal': }
  package{'libheimntlm0-heimdal': }
  package{'libhogweed2': }
  package{'libhpmud0': }
  package{'libhtml-form-perl': }
  package{'libhtml-format-perl': }
  package{'libhtml-parser-perl': }
  package{'libhtml-tagset-perl': }
  package{'libhtml-template-perl': }
  package{'libhtml-tree-perl': }
  package{'libhttp-cookies-perl': }
  package{'libhttp-daemon-perl': }
  package{'libhttp-date-perl': }
  package{'libhttp-message-perl': }
  package{'libhttp-negotiate-perl': }
  package{'libhunspell-1.3-0': }
  package{'libhwloc5': }
  package{'libhx509-5-heimdal': }
  package{'libibverbs1': }
  package{'libical1a': }
  package{'libice-dev': }
  package{'libice6': }
  package{'libicu52': }
  package{'libidn11': }
  package{'libidn11-dev': }
  package{'libiec61883-0': }
  package{'libieee1284-3': }
  package{'libijs-0.35': }
  package{'libilmbase6': }
  package{'libimobiledevice4': }
  package{'libintl-perl': }
  package{'libio-html-perl': }
  package{'libio-pty-perl': }
  package{'libio-socket-inet6-perl': }
  package{'libio-socket-ip-perl': }
  package{'libio-socket-ssl-perl': }
  package{'libio-stty-perl': }
  package{'libiodbc2': }
  package{'libirs-export91': }
  package{'libisc-export95': }
  package{'libisc95': }
  package{'libisccc90': }
  package{'libisccfg-export90': }
  package{'libisccfg90': }
  package{'libiscsi2': }
  package{'libisl10': }
  package{'libiso9660-8': }
  package{'libitm1': }
  package{'libiw-dev': }
  package{'libiw30': }
  package{'libjack-jackd2-0': }
  package{'libjasper1': }
  package{'libjavascriptcoregtk-1.0-0': }
  package{'libjbig0': }
  package{'libjbig2dec0': }
  package{'libjim0.75': }
  package{'libjpeg-dev': }
  package{'libjpeg62-turbo': }
  package{'libjpeg62-turbo-dev': }
  package{'libjs-excanvas': }
  package{'libjs-jquery': }
  package{'libjson-c2': }
  package{'libjson-glib-1.0-0': }
  package{'libjson-glib-1.0-common': }
  package{'libk5crypto3': }
  package{'libkabc4': }
  package{'libkactivities-models1': }
  package{'libkactivities6': }
  package{'libkalarmcal2': }
  package{'libkate1': }
  package{'libkatepartinterfaces4': }
  package{'libkcal4': }
  package{'libkcalcore4': }
  package{'libkcalutils4': }
  package{'libkcmutils4': }
  package{'libkdc2-heimdal': }
  package{'libkde3support4': }
  package{'libkdeclarative5': }
  package{'libkdecorations4abi2': }
  package{'libkdecore5': }
  package{'libkdesu5': }
  package{'libkdeui5': }
  package{'libkdewebkit5': }
  package{'libkdnssd4': }
  package{'libkemoticons4': }
  package{'libkephal4abi1': }
  package{'libkeyutils1': }
  package{'libkfile4': }
  package{'libkgapi2-2': }
  package{'libkholidays4': }
  package{'libkhtml5': }
  package{'libkidletime4': }
  package{'libkimap4': }
  package{'libkio5': }
  package{'libkjsapi4': }
  package{'libkjsembed4': }
  package{'libkldap4': }
  package{'libklibc': }
  package{'libkmbox4': }
  package{'libkmediaplayer4': }
  package{'libkmime4': }
  package{'libkmod2': }
  package{'libknewstuff3-4': }
  package{'libknotifyconfig4': }
  package{'libkntlm4': }
  package{'libkparts4': }
  package{'libkpimidentities4': }
  package{'libkpimtextedit4': }
  package{'libkpimutils4': }
  package{'libkprintutils4': }
  package{'libkpty4': }
  package{'libkrb5-26-heimdal': }
  package{'libkrb5-3': }
  package{'libkrb5-dev': }
  package{'libkrb5support0': }
  package{'libkresources4': }
  package{'libkrosscore4': }
  package{'libksba8': }
  package{'libkscreen1': }
  package{'libkscreensaver5': }
  package{'libksgrd4': }
  package{'libksignalplotter4': }
  package{'libktexteditor4': }
  package{'libkunitconversion4': }
  package{'libkutils4': }
  package{'libkwineffects1abi5': }
  package{'libkwinglesutils1': }
  package{'libkwinglutils1abi2': }
  package{'libkworkspace4abi2': }
  package{'libkxmlrpcclient4': }
  package{'liblapack-dev': }
  package{'liblapack3': }
  package{'liblcms2-2': }
  package{'liblcms2-utils': }
  package{'libldap-2.4-2': }
  package{'libldap2-dev': }
  package{'libldb1': }
  package{'liblircclient0': }
  package{'liblist-moreutils-perl': }
  package{'liblivemedia23': }
  package{'libllvm3.5': }
  package{'liblocale-gettext-perl': }
  package{'liblockfile-bin': }
  package{'liblockfile1': }
  package{'liblog-message-perl': }
  package{'liblog-message-simple-perl': }
  package{'liblogging-stdlog0': }
  package{'liblognorm1': }
  package{'liblqr-1-0': }
  package{'liblsan0': }
  package{'libltdl-dev': }
  package{'libltdl7': }
  package{'liblua5.1-0': }
  package{'liblua5.2-0': }
  package{'liblvm2app2.2': }
  package{'liblvm2cmd2.02': }
  package{'liblwp-mediatypes-perl': }
  package{'liblwp-protocol-https-perl': }
  package{'liblwres90': }
  package{'liblz4-1': }
  package{'liblzma-dev': }
  package{'liblzma5': }
  package{'liblzo2-2': }
  package{'libmad0': }
  package{'libmagic1': }
  package{'libmagickcore-6.q16-2-extra': }
  package{'libmail-sendmail-perl': }
  package{'libmail-spf-perl': }
  package{'libmailtools-perl': }
  package{'libmailtransport4': }
  package{'libmbim-glib4': }
  package{'libmbim-proxy': }
  package{'libmhash2': }
  package{'libmicroblog4': }
  package{'libmm-glib0': }
  package{'libmng1': }
  package{'libmodplug1': }
  package{'libmodule-build-perl': }
  package{'libmodule-pluggable-perl': }
  package{'libmodule-signature-perl': }
  package{'libmount1': }
  package{'libmp3lame0': }
  package{'libmpc3': }
  package{'libmpcdec6': }
  package{'libmpdec2': }
  package{'libmpeg2-4': }
  package{'libmpfr4': }
  package{'libmtdev1': }
  package{'libmtp9': }
  package{'libmysqlclient18': }
  package{'libncurses5': }
  package{'libncurses5-dev': }
  package{'libncursesw5': }
  package{'libnepomuk4': }
  package{'libnepomukcore4': }
  package{'libnepomukquery4a': }
  package{'libnepomukutils4': }
  package{'libnet-dbus-perl': }
  package{'libnet-dns-perl': }
  package{'libnet-domain-tld-perl': }
  package{'libnet-http-perl': }
  package{'libnet-ip-perl': }
  package{'libnet-ipv6addr-perl': }
  package{'libnet-netmask-perl': }
  package{'libnet-smtp-ssl-perl': }
  package{'libnet-ssleay-perl': }
  package{'libnetaddr-ip-perl': }
  package{'libnetpbm10': }
  package{'libnettle4': }
  package{'libnetwork-ipv4addr-perl': }
  package{'libnewt0.52': }
  package{'libnfnetlink0': }
  package{'libnfsidmap2': }
  package{'libnl-3-200': }
  package{'libnl-genl-3-200': }
  package{'libnl-route-3-200': }
  package{'libnotify4': }
  package{'libnspr4': }
  package{'libnss-winbind': }
  package{'libnss3': }
  package{'libntdb1': }
  package{'libntrack-qt4-1': }
  package{'libntrack0': }
  package{'libnuma1': }
  package{'libodbc1': }
  package{'libogg0': }
  package{'libonig2': }
  package{'libopenexr6': }
  package{'libopenjpeg5': }
  package{'libopenvg1-mesa': }
  package{'libopus0': }
  package{'liborbit-2-0': }
  package{'liborbit2': }
  package{'liborc-0.4-0': }
  package{'libossp-uuid16': }
  package{'libp11-kit-dev': }
  package{'libp11-kit0': }
  package{'libpackage-constants-perl': }
  package{'libpam-cap': }
  package{'libpam-ck-connector': }
  package{'libpam-modules': }
  package{'libpam-modules-bin': }
  package{'libpam-runtime': }
  package{'libpam-systemd': }
  package{'libpam-winbind': }
  package{'libpam0g': }
  package{'libpango-1.0-0': }
  package{'libpango-perl': }
  package{'libpango1.0-0': }
  package{'libpangocairo-1.0-0': }
  package{'libpangoft2-1.0-0': }
  package{'libpangox-1.0-0': }
  package{'libpangoxft-1.0-0': }
  package{'libpaper-utils': }
  package{'libpaper1': }
  package{'libparted2': }
  package{'libpathplan4': }
  package{'libpci3': }
  package{'libpciaccess0': }
  package{'libpcre3': }
  package{'libpcre3-dev': }
  package{'libpcsclite1': }
  package{'libperl4-corelibs-perl': }
  package{'libphonon4': }
  package{'libpipeline1': }
  package{'libpixman-1-0': }
  package{'libplasma-geolocation-interface4': }
  package{'libplasma3': }
  package{'libplasmaclock4abi4': }
  package{'libplasmagenericshell4': }
  package{'libplist2': }
  package{'libpng12-0': }
  package{'libpng12-dev': }
  package{'libpod-latex-perl': }
  package{'libpod-readme-perl': }
  package{'libpolkit-agent-1-0': }
  package{'libpolkit-backend-1-0': }
  package{'libpolkit-gobject-1-0': }
  package{'libpolkit-qt-1-1': }
  package{'libpoppler46': }
  package{'libpopt0': }
  package{'libpostproc52': }
  package{'libpq5': }
  package{'libprison0': }
  package{'libprocesscore4abi1': }
  package{'libprocessui4a': }
  package{'libprocps3': }
  package{'libpsl0': }
  package{'libpth20': }
  package{'libpthread-stubs0-dev': }
  package{'libpulse-mainloop-glib0': }
  package{'libpulse0': }
  package{'libqalculate5': }
  package{'libqca2': }
  package{'libqdbm14': }
  package{'libqimageblitz4': }
  package{'libqjson0': }
  package{'libqmi-glib1': }
  package{'libqmi-proxy': }
  package{'libqpdf13': }
  package{'libqrencode3': }
  package{'libqt4-declarative': }
  package{'libqt4-designer': }
  package{'libqt4-help': }
  package{'libqt4-network': }
  package{'libqt4-opengl': }
  package{'libqt4-qt3support': }
  package{'libqt4-script': }
  package{'libqt4-scripttools': }
  package{'libqt4-sql': }
  package{'libqt4-svg': }
  package{'libqt4-test': }
  package{'libqt4-xml': }
  package{'libqt4-xmlpatterns': }
  package{'libqtassistantclient4': }
  package{'libqtcore4': }
  package{'libqtdbus4': }
  package{'libqtgui4': }
  package{'libqtruby4shared2': }
  package{'libqtwebkit4': }
  package{'libquadmath0': }
  package{'librados2': }
  package{'libraptor2-0': }
  package{'librarian0': }
  package{'librasqal3': }
  package{'libraw1394-11': }
  package{'librbd1': }
  package{'librdf0': }
  package{'libreadline-dev': }
  package{'libreadline5': }
  package{'libreadline6': }
  package{'libreadline6-dev': }
  package{'libregexp-common-perl': }
  package{'libresid-builder0c2a': }
  package{'librest-0.7-0': }
  package{'libroken18-heimdal': }
  package{'librpm3': }
  package{'librpmbuild3': }
  package{'librpmio3': }
  package{'librsvg2-2': }
  package{'librsvg2-common': }
  package{'librtmp-dev': }
  package{'librtmp1': }
  package{'libruby2.1': }
  package{'libsamplerate0': }
  package{'libsane': }
  package{'libsane-common': }
  package{'libsane-extras': }
  package{'libsane-extras-common': }
  package{'libsane-hpaio': }
  package{'libsasl2-2': }
  package{'libsasl2-modules': }
  package{'libsasl2-modules-db': }
  package{'libschroedinger-1.0-0': }
  package{'libsctp1': }
  package{'libsdl-image1.2': }
  package{'libsdl1.2debian': }
  package{'libseccomp2': }
  package{'libsecret-1-0': }
  package{'libsecret-common': }
  package{'libselinux1': }
  package{'libsemanage-common': }
  package{'libsemanage1': }
  package{'libsensors4': }
  package{'libsepol1': }
  package{'libsgutils2-2': }
  package{'libshine3': }
  package{'libshout3': }
  package{'libsidplay2': }
  package{'libsigsegv2': }
  package{'libslang2': }
  package{'libslp1': }
  package{'libsm-dev': }
  package{'libsm6': }
  package{'libsmartcols1': }
  package{'libsmbclient': }
  package{'libsmokeqtcore4-3': }
  package{'libsmokeqtdbus4-3': }
  package{'libsmokeqtgui4-3': }
  package{'libsmokeqtnetwork4-3': }
  package{'libsmokeqtopengl4-3': }
  package{'libsmokeqtsql4-3': }
  package{'libsmokeqtsvg4-3': }
  package{'libsmokeqtxml4-3': }
  package{'libsndfile1': }
  package{'libsnmp-base': }
  package{'libsnmp30': }
  package{'libsocket-perl': }
  package{'libsocket6-perl': }
  package{'libsolid4': }
  package{'libsoprano4': }
  package{'libsoup-gnome2.4-1': }
  package{'libsoup2.4-1': }
  package{'libspeex1': }
  package{'libspeexdsp1': }
  package{'libspice-server1': }
  package{'libsqlite3-0': }
  package{'libss2': }
  package{'libssh-4': }
  package{'libssh-gcrypt-4': }
  package{'libssh2-1': }
  package{'libssh2-1-dev': }
  package{'libssl-dev': }
  package{'libssl-doc': }
  package{'libssl1.0.0': }
  package{'libstdc++-4.9-dev': }
  package{'libstdc++6': }
  package{'libstreams0': }
  package{'libswitch-perl': }
  package{'libswscale3': }
  package{'libsyndication4': }
  package{'libsys-hostname-long-perl': }
  package{'libsystemd-login0': }
  package{'libsystemd0': }
  package{'libtalloc2': }
  package{'libtar0': }
  package{'libtaskmanager4abi4': }
  package{'libtasn1-6': }
  package{'libtasn1-6-dev': }
  package{'libtasn1-doc': }
  package{'libtcl8.5': }
  package{'libtcl8.6': }
  package{'libtdb1': }
  package{'libterm-readkey-perl': }
  package{'libterm-size-perl': }
  package{'libterm-ui-perl': }
  package{'libtevent0': }
  package{'libtext-charwidth-perl': }
  package{'libtext-iconv-perl': }
  package{'libtext-soundex-perl': }
  package{'libtext-template-perl': }
  package{'libtext-unidecode-perl': }
  package{'libtext-wrapi18n-perl': }
  package{'libthai-data': }
  package{'libthai0': }
  package{'libtheora0': }
  package{'libthreadweaver4': }
  package{'libtie-ixhash-perl': }
  package{'libtiff5': }
  package{'libtimedate-perl': }
  package{'libtinfo-dev': }
  package{'libtinfo5': }
  package{'libtirpc1': }
  package{'libtk8.5': }
  package{'libtk8.6': }
  package{'libtokyocabinet9': }
  package{'libtool': }
  package{'libtsan0': }
  package{'libtwolame0': }
  package{'libtxc-dxtn-s2tc0': }
  package{'libubsan0': }
  package{'libudev1': }
  package{'libudisks2-0': }
  package{'libunistring0': }
  package{'libunwind8': }
  package{'libupnp6': }
  package{'libupower-glib3': }
  package{'liburi-perl': }
  package{'libusageenvironment1': }
  package{'libusb-0.1-4': }
  package{'libusb-1.0-0': }
  package{'libusbmuxd2': }
  package{'libusbredirparser1': }
  package{'libustr-1.0-1': }
  package{'libutempter0': }
  package{'libuuid-perl': }
  package{'libuuid-tiny-perl': }
  package{'libuuid1': }
  package{'libv4l-0': }
  package{'libv4lconvert0': }
  package{'libva-drm1': }
  package{'libva-x11-1': }
  package{'libva1': }
  package{'libvcdinfo0': }
  package{'libvdeplug2': }
  package{'libvdpau1': }
  package{'libvirtodbc0': }
  package{'libvisual-0.4-0': }
  package{'libvisual-0.4-plugins': }
  package{'libvlc5': }
  package{'libvlccore8': }
  package{'libvncclient0': }
  package{'libvorbis0a': }
  package{'libvorbisenc2': }
  package{'libvorbisfile3': }
  package{'libvpx1': }
  package{'libvte-2.90-9': }
  package{'libvte-2.90-common': }
  package{'libvte9': }
  package{'libwavpack1': }
  package{'libwayland-client0': }
  package{'libwayland-cursor0': }
  package{'libwayland-egl1-mesa': }
  package{'libwayland-server0': }
  package{'libwbclient0': }
  package{'libweather-ion6': }
  package{'libwebkit1.1-cil': }
  package{'libwebkitgtk-1.0-0': }
  package{'libwebp5': }
  package{'libwebpdemux1': }
  package{'libwebpmux1': }
  package{'libwind0-heimdal': }
  package{'libwinpr-crt0.1': }
  package{'libwinpr-crypto0.1': }
  package{'libwinpr-dsparse0.1': }
  package{'libwinpr-environment0.1': }
  package{'libwinpr-file0.1': }
  package{'libwinpr-handle0.1': }
  package{'libwinpr-heap0.1': }
  package{'libwinpr-input0.1': }
  package{'libwinpr-interlocked0.1': }
  package{'libwinpr-library0.1': }
  package{'libwinpr-path0.1': }
  package{'libwinpr-pool0.1': }
  package{'libwinpr-registry0.1': }
  package{'libwinpr-rpc0.1': }
  package{'libwinpr-sspi0.1': }
  package{'libwinpr-synch0.1': }
  package{'libwinpr-sysinfo0.1': }
  package{'libwinpr-thread0.1': }
  package{'libwinpr-utils0.1': }
  package{'libwmf0.2-7': }
  package{'libwrap0': }
  package{'libwww-perl': }
  package{'libwww-robotrules-perl': }
  package{'libx11-6': }
  package{'libx11-data': }
  package{'libx11-dev': }
  package{'libx11-doc': }
  package{'libx11-protocol-perl': }
  package{'libx11-xcb-dev': }
  package{'libx11-xcb1': }
  package{'libx264-142': }
  package{'libx32asan1': }
  package{'libx32atomic1': }
  package{'libx32cilkrts5': }
  package{'libx32gcc-4.9-dev': }
  package{'libx32gcc1': }
  package{'libx32gomp1': }
  package{'libx32itm1': }
  package{'libx32quadmath0': }
  package{'libx32stdc++-4.9-dev': }
  package{'libx32stdc++6': }
  package{'libx32ubsan0': }
  package{'libx86-1': }
  package{'libxapian22': }
  package{'libxatracker2': }
  package{'libxau-dev': }
  package{'libxau6': }
  package{'libxaw7': }
  package{'libxcb-composite0': }
  package{'libxcb-damage0': }
  package{'libxcb-dri3-0': }
  package{'libxcb-dri3-dev': }
  package{'libxcb-glx0': }
  package{'libxcb-glx0-dev': }
  package{'libxcb-image0': }
  package{'libxcb-keysyms1': }
  package{'libxcb-present-dev': }
  package{'libxcb-present0': }
  package{'libxcb-randr0': }
  package{'libxcb-randr0-dev': }
  package{'libxcb-render0': }
  package{'libxcb-render0-dev': }
  package{'libxcb-shape0': }
  package{'libxcb-shape0-dev': }
  package{'libxcb-shm0': }
  package{'libxcb-sync-dev': }
  package{'libxcb-sync1': }
  package{'libxcb-util0': }
  package{'libxcb-xfixes0': }
  package{'libxcb-xfixes0-dev': }
  package{'libxcb-xtest0': }
  package{'libxcb-xv0': }
  package{'libxcb1': }
  package{'libxcb1-dev': }
  package{'libxcomposite1': }
  package{'libxcursor1': }
  package{'libxdamage-dev': }
  package{'libxdamage1': }
  package{'libxdmcp-dev': }
  package{'libxdmcp6': }
  package{'libxdot4': }
  package{'libxen-4.4': }
  package{'libxenstore3.0': }
  package{'libxerces-c3.1': }
  package{'libxext-dev': }
  package{'libxext6': }
  package{'libxfixes-dev': }
  package{'libxfixes3': }
  package{'libxfont1': }
  package{'libxft2': }
  package{'libxi6': }
  package{'libxinerama1': }
  package{'libxkbcommon0': }
  package{'libxkbfile1': }
  package{'libxmu6': }
  package{'libxmuu1': }
  package{'libxpm4': }
  package{'libxrandr2': }
  package{'libxrender1': }
  package{'libxshmfence-dev': }
  package{'libxshmfence1': }
  package{'libxslt1.1': }
  package{'libxss1': }
  package{'libxt-dev': }
  package{'libxt6': }
  package{'libxtables10': }
  package{'libxtst6': }
  package{'libxv1': }
  package{'libxvidcore4': }
  package{'libxvmc1': }
  package{'libxxf86dga1': }
  package{'libxxf86vm-dev': }
  package{'libxxf86vm1': }
  package{'libyajl2': }
  package{'libyaml-0-2': }
  package{'libzvbi0': }
  package{'linux-base': }
  package{'linux-image-3.16.0-4-amd64': }
  package{'linux-image-amd64': }
  package{'linux-libc-dev': }
  package{'linux-tools': }
  package{'lksctp-tools': }
  package{'locales': }
  package{'login': }
  package{'logrotate': }
  package{'lsb-base': }
  package{'lsb-release': }
  package{'lshw': }
  package{'lsof': }
  package{'lvm2': }
  package{'m4': }
  package{'mailagent': }
  package{'make': }
  package{'man-db': }
  package{'manpages': }
  package{'manpages-dev': }
  package{'mawk': }
  package{'mercurial': }
  package{'mercurial-common': }
  package{'mesa-common-dev': }
  package{'mesa-utils': }
  package{'mime-support': }
  package{'mingw-w64-common': }
  package{'mingw-w64-i686-dev': }
  package{'mingw32': }
  package{'mingw32-binutils': }
  package{'mlocate': }
  package{'modemmanager': }
  package{'monodoc-base': }
  package{'monodoc-browser': }
  package{'monodoc-manual': }
  package{'mount': }
  package{'mscompress': }
  package{'multiarch-support': }
  package{'mutt': }
  package{'nano': }
  package{'ncurses-base': }
  package{'ncurses-bin': }
  package{'ncurses-term': }
  package{'net-tools': }
  package{'netbase': }
  package{'netcat-traditional': }
  package{'netpbm': }
  package{'nettle-dev': }
  package{'nfs-common': }
  package{'nfs-kernel-server': }
  package{'notification-daemon': }
  package{'ntfs-3g': }
  package{'ntp':}
  package{'ntrack-module-libnl-0': }
  package{'ocl-icd-libopencl1': }
  package{'odbcinst': }
  package{'odbcinst1debian2': }
  package{'openbsd-inetd': }
  package{'openprinting-ppds': }
  package{'openssh-client': }
  package{'openssh-server': }
  package{'openssh-sftp-server': }
  package{'openssl': }
  package{'os-prober': }
  package{'oxygen-icon-theme': }
  package{'oxygencursors': }
  package{'parallel': }
  package{'parted': }
  package{'passwd': }
  package{'patch': }
  package{'pciutils': }
  package{'phonon': }
  package{'pinentry-gtk2': }
  package{'pkg-config': }
  package{'plasma-scriptengine-superkaramba': }
  package{'plasma-widgets-workspace': }
  package{'pm-utils': }
  package{'po-debconf': }
  package{'policykit-1': }
  package{'policykit-1-gnome': }
  package{'polkit-kde-1': }
  package{'poppler-data': }
  package{'poppler-utils': }
  package{'popularity-contest': }
  package{'procmail': }
  package{'procps': }
  package{'psmisc': }
  package{'psutils': }
  package{'qemu-system-common': }
  package{'qemu-system-x86': }
  package{'qemu-utils': }
  package{'qpdf': }
  package{'rabbitmq-server': }
  package{'rarian-compat': }
  package{'re2c': }
  package{'readline-common': }
  package{'rename': }
  package{'reportbug': }
  package{'rinse': }
  package{'rpcbind': }
  package{'rpm': }
  package{'rpm-common': }
  package{'rpm2cpio': }
  package{'rsync': }
  package{'rsyslog': }
  package{'sa-compile': }
  package{'sa-exim': }
  package{'sane-utils': }
  package{'seabios': }
  package{'sed': }
  package{'sensible-utils': }
  package{'sgml-base': }
  package{'sgml-data': }
  package{'shared-mime-info': }
  package{'sharutils': }
  package{'smartmontools': }
  package{'smbclient': }
  package{'software-properties-common': }
  package{'software-properties-gtk': }
  package{'spamassassin': }
  package{'spamc': }
  package{'sqlite3': }
  package{'ssl-cert': }
  package{'startpar': }
  package{'strace': }
  package{'sudo': }
  package{'synaptic': }
  package{'systemd': }
  package{'systemd-sysv': }
  package{'systemsettings': }
  package{'sysv-rc': }
  package{'sysvinit': }
  package{'sysvinit-utils': }
  package{'tar': }
  package{'task-english': }
  package{'task-print-server': }
  package{'task-ssh-server': }
  package{'tasksel': }
  package{'tasksel-data': }
  package{'tcl': }
  package{'tcl8.5': }
  package{'tcl8.6': }
  package{'tcpd': }
  package{'tdb-tools': }
  package{'telnet': }
  package{'texinfo': }
  package{'time': }
  package{'tk': }
  package{'tk8.5': }
  package{'tk8.6': }
  package{'tk8.6-blt2.5': }
  package{'tofrodos': }
  package{'traceroute': }
  package{'ttf-dejavu-extra': }
  package{'tzdata': }
  package{'ucf': }
  package{'udev': }
  package{'udisks': }
  package{'udisks2': }
  package{'unattended-upgrades': }
  package{'unzip': }
  package{'update-inetd': }
  package{'upower': }
  package{'usb-modeswitch': }
  package{'usb-modeswitch-data': }
  package{'usbutils': }
  package{'util-linux': }
  package{'util-linux-locales': }
  package{'uuid': }
  package{'valgrind': }
  package{'valgrind-dbg': }
  package{'vim': }
  package{'vim-common': }
  package{'vim-runtime': }
  package{'vim-tiny': }
  package{'vlc': }
  package{'vlc-data': }
  package{'w3m': }
  package{'wamerican': }
  package{'wamerican-huge': }
  package{'wbritish-huge': }
  package{'wget': }
  package{'whiptail': }
  package{'whois': }
  package{'winbind': }
  package{'wpasupplicant': }
  package{'xauth': }
  package{'xbitmaps': }
  package{'xdg-user-dirs': }
  package{'xdg-utils': }
  package{'xen-hypervisor-4.4-amd64': }
  package{'xen-system-amd64': }
  package{'xen-tools': }
  package{'xen-utils-4.4': }
  package{'xen-utils-common': }
  package{'xenstore-utils': }
  package{'xfonts-100dpi': }
  package{'xfonts-75dpi': }
  package{'xfonts-base': }
  package{'xfonts-encodings': }
  package{'xfonts-scalable': }
  package{'xfonts-utils': }
  package{'xinit': }
  package{'xkb-data': }
  package{'xml-core': }
  package{'xmlstarlet': }
  package{'xorg': }
  package{'xorg-docs-core': }
  package{'xorg-sgml-doctools': }
  package{'xsltproc': }
  package{'xterm': }
  package{'xtrans-dev': }
  package{'xvfb': }
  package{'xz-utils': }
  package{'yasm': }
  package{'zip': }
  package{'zlib1g': }
  package{'zlib1g-dev': }
}
